-- ============================================================
-- INTEGRACIÓN TURISMO + VINOTECA
-- Portado de Oracle/PL-SQL (documento original del equipo) a
-- PostgreSQL, para correr en el editor SQL de Supabase.
--
-- Cambios respecto del documento original (para la defensa):
--   1. VARCHAR2 -> VARCHAR, NUMBER -> INTEGER/NUMERIC, SYSDATE -> CURRENT_DATE
--      (el resto de la sintaxis DDL es prácticamente idéntica).
--   2. Los PROCEDURE/TRIGGER de PL/SQL se reescribieron como
--      FUNCTION ... LANGUAGE plpgsql (equivalente en Postgres).
--   3. Se agregó password_hash en cliente (login web, no estaba
--      contemplado en el modelo original).
--   4. Se agregó precio en pasaje, hotel y circuito, e imagen_url
--      en vino (necesarios para mostrar precios/fotos en la web;
--      el documento original no los definía).
--   Todo lo demás -tablas, relaciones, reglas de millas/categoría/
--   catálogo exclusivo- es el diseño original del equipo.
-- ============================================================

-- Borrado limpio para poder re-ejecutar este script en Supabase
DROP TABLE IF EXISTS linea_venta_vino CASCADE;
DROP TABLE IF EXISTS venta_vino CASCADE;
DROP TABLE IF EXISTS movimiento_stock CASCADE;
DROP TABLE IF EXISTS stock CASCADE;
DROP TABLE IF EXISTS vino CASCADE;
DROP TABLE IF EXISTS bodega CASCADE;
DROP TABLE IF EXISTS reserva_participante CASCADE;
DROP TABLE IF EXISTS participante CASCADE;
DROP TABLE IF EXISTS reserva CASCADE;
DROP TABLE IF EXISTS pasaje CASCADE;
DROP TABLE IF EXISTS circuito_ciudad CASCADE;
DROP TABLE IF EXISTS circuito CASCADE;
DROP TABLE IF EXISTS hotel CASCADE;
DROP TABLE IF EXISTS agencia_mayorista CASCADE;
DROP TABLE IF EXISTS mayorista CASCADE;
DROP TABLE IF EXISTS agencia CASCADE;
DROP TABLE IF EXISTS cliente CASCADE;
DROP TABLE IF EXISTS categoria_cliente CASCADE;
DROP TABLE IF EXISTS aeropuerto CASCADE;
DROP TABLE IF EXISTS ciudad CASCADE;
DROP TABLE IF EXISTS provincia CASCADE;
DROP TABLE IF EXISTS pais CASCADE;

-- ===== Ubicación (compartida) =====
CREATE TABLE pais (
  codigo   CHAR(3) PRIMARY KEY,
  nombre   VARCHAR(80) NOT NULL
);

CREATE TABLE provincia (
  provincia_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR(100) NOT NULL,
  pais_codigo    CHAR(3) NOT NULL REFERENCES pais(codigo)
);

CREATE TABLE ciudad (
  ciudad_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR(100) NOT NULL,
  provincia_id   INTEGER NOT NULL REFERENCES provincia(provincia_id)
);

CREATE TABLE aeropuerto (
  codigo             VARCHAR(4) PRIMARY KEY,
  nombre             VARCHAR(100) NOT NULL,
  cant_vuelos_prom   INTEGER,
  pais_codigo        CHAR(3) NOT NULL REFERENCES pais(codigo)
);

-- ===== Cliente y fidelización (integración) =====
CREATE TABLE categoria_cliente (
  categoria_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre             VARCHAR(30) NOT NULL,
  nivel              INTEGER NOT NULL,
  millas_minimas     INTEGER NOT NULL,
  descuento_pct      NUMERIC(5,2) DEFAULT 0 NOT NULL,
  acceso_exclusivo   CHAR(1) DEFAULT 'N' CHECK (acceso_exclusivo IN ('S','N')),
  CONSTRAINT uk_categoria_nivel UNIQUE (nivel)
);

CREATE TABLE cliente (
  dni                  VARCHAR(15) PRIMARY KEY,
  nombre               VARCHAR(60) NOT NULL,
  apellido             VARCHAR(60) NOT NULL,
  email                VARCHAR(120) UNIQUE NOT NULL,
  telefono             VARCHAR(30),
  password_hash        VARCHAR(255) NOT NULL,
  millas_acumuladas    INTEGER DEFAULT 0 NOT NULL,
  categoria_id         INTEGER NOT NULL REFERENCES categoria_cliente(categoria_id)
);

-- ===== Turismo =====
CREATE TABLE agencia (
  agencia_id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cant_empleados     INTEGER CHECK (cant_empleados >= 0),
  direccion_fisica   VARCHAR(200) NOT NULL
);

CREATE TABLE mayorista (
  mayorista_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                    VARCHAR(120) NOT NULL,
  facturacion_prom_anual    NUMERIC(14,2)
);

CREATE TABLE agencia_mayorista (
  agencia_id     INTEGER NOT NULL REFERENCES agencia(agencia_id),
  mayorista_id   INTEGER NOT NULL REFERENCES mayorista(mayorista_id),
  PRIMARY KEY (agencia_id, mayorista_id)
);

CREATE TABLE hotel (
  hotel_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre         VARCHAR(100) NOT NULL,
  categoria      INTEGER,
  direccion      VARCHAR(200),
  precio_noche   NUMERIC(10,2) NOT NULL DEFAULT 0,
  ciudad_id      INTEGER NOT NULL REFERENCES ciudad(ciudad_id)
);

CREATE TABLE circuito (
  circuito_id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  denominacion                VARCHAR(120) NOT NULL,
  cant_personas_anual_prom    INTEGER,
  precio                      NUMERIC(10,2) NOT NULL DEFAULT 0
);

CREATE TABLE circuito_ciudad (
  circuito_id   INTEGER NOT NULL REFERENCES circuito(circuito_id),
  ciudad_id     INTEGER NOT NULL REFERENCES ciudad(ciudad_id),
  PRIMARY KEY (circuito_id, ciudad_id)
);

CREATE TABLE pasaje (
  pasaje_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descripcion         VARCHAR(200),
  horario_vuelo       TIMESTAMP,
  precio              NUMERIC(10,2) NOT NULL DEFAULT 0,
  millas_otorgadas    INTEGER DEFAULT 0 NOT NULL,
  aero_salida_id      VARCHAR(4) NOT NULL REFERENCES aeropuerto(codigo),
  aero_llegada_id     VARCHAR(4) NOT NULL REFERENCES aeropuerto(codigo)
);

CREATE TABLE reserva (
  reserva_id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_reserva        DATE DEFAULT CURRENT_DATE NOT NULL,
  codigo_vuelo         VARCHAR(20),
  millas_generadas     INTEGER DEFAULT 0,
  cliente_dni          VARCHAR(15) NOT NULL REFERENCES cliente(dni),
  agencia_id           INTEGER NOT NULL REFERENCES agencia(agencia_id),
  pasaje_id            INTEGER REFERENCES pasaje(pasaje_id),
  hotel_id             INTEGER REFERENCES hotel(hotel_id),
  circuito_id          INTEGER REFERENCES circuito(circuito_id),
  CONSTRAINT ck_reserva_tipo CHECK (
    pasaje_id IS NOT NULL OR hotel_id IS NOT NULL OR circuito_id IS NOT NULL
  )
);

CREATE TABLE participante (
  participante_dni   VARCHAR(15) PRIMARY KEY,
  nombre             VARCHAR(60) NOT NULL,
  apellido           VARCHAR(60) NOT NULL,
  cliente_dni        VARCHAR(15) NOT NULL REFERENCES cliente(dni)
);

CREATE TABLE reserva_participante (
  reserva_id          INTEGER NOT NULL REFERENCES reserva(reserva_id) ON DELETE CASCADE,
  participante_dni     VARCHAR(15) NOT NULL REFERENCES participante(participante_dni),
  nro_asiento          VARCHAR(10),
  PRIMARY KEY (reserva_id, participante_dni)
);

-- ===== Vinoteca =====
CREATE TABLE bodega (
  bodega_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      VARCHAR(120) NOT NULL,
  contacto    VARCHAR(120)
);

CREATE TABLE vino (
  vino_id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                 VARCHAR(200) NOT NULL,
  varietal               VARCHAR(100),
  anio                   INTEGER,
  precio                 NUMERIC(10,2) CHECK (precio > 0),
  bodega_id              INTEGER NOT NULL REFERENCES bodega(bodega_id),
  categoria_minima_id    INTEGER REFERENCES categoria_cliente(categoria_id),
  imagen_url             VARCHAR(300)
);

CREATE TABLE stock (
  stock_id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vino_id                 INTEGER NOT NULL UNIQUE REFERENCES vino(vino_id),
  cantidad                INTEGER DEFAULT 0 NOT NULL,
  ultima_actualizacion     DATE DEFAULT CURRENT_DATE
);

CREATE TABLE movimiento_stock (
  mov_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vino_id    INTEGER NOT NULL REFERENCES vino(vino_id),
  tipo       VARCHAR(20) CHECK (tipo IN ('INGRESO','SALIDA')),
  cantidad   INTEGER NOT NULL,
  fecha      DATE DEFAULT CURRENT_DATE
);

CREATE TABLE venta_vino (
  venta_id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_dni            VARCHAR(15) NOT NULL REFERENCES cliente(dni),
  fecha                  DATE DEFAULT CURRENT_DATE,
  total                  NUMERIC(12,2),
  descuento_aplicado     NUMERIC(5,2) DEFAULT 0
);

CREATE TABLE linea_venta_vino (
  linea_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id           INTEGER NOT NULL REFERENCES venta_vino(venta_id) ON DELETE CASCADE,
  vino_id            INTEGER NOT NULL REFERENCES vino(vino_id),
  cantidad           INTEGER NOT NULL CHECK (cantidad > 0),
  precio_unitario    NUMERIC(10,2) NOT NULL
);

-- ============================================================
-- FUNCIONES Y TRIGGERS DE INTEGRACIÓN
-- (equivalentes en plpgsql al PL/SQL del documento original)
-- ============================================================

-- 1) Recalcular categoría del cliente según sus millas
CREATE OR REPLACE FUNCTION prc_actualizar_categoria(p_dni VARCHAR)
RETURNS VOID AS $$
DECLARE
  v_categoria_id INTEGER;
BEGIN
  SELECT categoria_id INTO v_categoria_id
  FROM categoria_cliente
  WHERE millas_minimas <= (SELECT millas_acumuladas FROM cliente WHERE dni = p_dni)
  ORDER BY millas_minimas DESC
  FETCH FIRST 1 ROW ONLY;

  UPDATE cliente SET categoria_id = v_categoria_id WHERE dni = p_dni;
END;
$$ LANGUAGE plpgsql;

-- 2) BEFORE INSERT en reserva: copia las millas del pasaje (si hay)
CREATE OR REPLACE FUNCTION trg_reserva_bi_fn()
RETURNS TRIGGER AS $$
DECLARE
  v_millas INTEGER;
BEGIN
  IF NEW.pasaje_id IS NOT NULL THEN
    SELECT millas_otorgadas INTO v_millas FROM pasaje WHERE pasaje_id = NEW.pasaje_id;
    NEW.millas_generadas := v_millas;
  ELSE
    NEW.millas_generadas := 0;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reserva_bi
BEFORE INSERT ON reserva
FOR EACH ROW EXECUTE FUNCTION trg_reserva_bi_fn();

-- 3) AFTER INSERT en reserva: suma millas al cliente y recalcula categoría
CREATE OR REPLACE FUNCTION trg_reserva_ai_fn()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.millas_generadas > 0 THEN
    UPDATE cliente
    SET millas_acumuladas = millas_acumuladas + NEW.millas_generadas
    WHERE dni = NEW.cliente_dni;

    PERFORM prc_actualizar_categoria(NEW.cliente_dni);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_reserva_ai
AFTER INSERT ON reserva
FOR EACH ROW EXECUTE FUNCTION trg_reserva_ai_fn();

-- 4) BEFORE INSERT en linea_venta_vino: valida acceso al catálogo exclusivo
CREATE OR REPLACE FUNCTION trg_linea_venta_bi_fn()
RETURNS TRIGGER AS $$
DECLARE
  v_categoria_min      INTEGER;
  v_cliente_dni        VARCHAR(15);
  v_nivel_cliente      INTEGER;
  v_nivel_requerido    INTEGER;
BEGIN
  SELECT categoria_minima_id INTO v_categoria_min FROM vino WHERE vino_id = NEW.vino_id;

  IF v_categoria_min IS NOT NULL THEN
    SELECT cliente_dni INTO v_cliente_dni FROM venta_vino WHERE venta_id = NEW.venta_id;

    SELECT cc.nivel INTO v_nivel_cliente
    FROM cliente c JOIN categoria_cliente cc ON c.categoria_id = cc.categoria_id
    WHERE c.dni = v_cliente_dni;

    SELECT nivel INTO v_nivel_requerido FROM categoria_cliente WHERE categoria_id = v_categoria_min;

    IF v_nivel_cliente < v_nivel_requerido THEN
      RAISE EXCEPTION 'El cliente no alcanza la categoria minima para comprar este vino exclusivo.';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_linea_venta_bi
BEFORE INSERT ON linea_venta_vino
FOR EACH ROW EXECUTE FUNCTION trg_linea_venta_bi_fn();

-- 5) Registrar venta de vino aplicando el descuento de categoría
--    (la Flask app la llama vía supabase.rpc(...))
CREATE OR REPLACE FUNCTION prc_registrar_venta_vino(
  p_cliente_dni VARCHAR,
  p_vino_id INTEGER,
  p_cantidad INTEGER
) RETURNS INTEGER AS $$
DECLARE
  v_venta_id       INTEGER;
  v_descuento_pct  NUMERIC;
  v_precio         NUMERIC;
  v_subtotal       NUMERIC;
  v_stock_actual   INTEGER;
BEGIN
  SELECT cantidad INTO v_stock_actual FROM stock WHERE vino_id = p_vino_id;
  IF v_stock_actual IS NULL OR v_stock_actual < p_cantidad THEN
    RAISE EXCEPTION 'No hay stock suficiente de este vino.';
  END IF;

  SELECT cc.descuento_pct INTO v_descuento_pct
  FROM cliente c JOIN categoria_cliente cc ON c.categoria_id = cc.categoria_id
  WHERE c.dni = p_cliente_dni;

  SELECT precio INTO v_precio FROM vino WHERE vino_id = p_vino_id;
  v_subtotal := v_precio * p_cantidad * (1 - v_descuento_pct / 100);

  INSERT INTO venta_vino (cliente_dni, fecha, total, descuento_aplicado)
  VALUES (p_cliente_dni, CURRENT_DATE, v_subtotal, v_descuento_pct)
  RETURNING venta_id INTO v_venta_id;

  INSERT INTO linea_venta_vino (venta_id, vino_id, cantidad, precio_unitario)
  VALUES (v_venta_id, p_vino_id, p_cantidad, v_precio);

  UPDATE stock SET cantidad = cantidad - p_cantidad, ultima_actualizacion = CURRENT_DATE
  WHERE vino_id = p_vino_id;

  INSERT INTO movimiento_stock (vino_id, tipo, cantidad)
  VALUES (p_vino_id, 'SALIDA', p_cantidad);

  RETURN v_venta_id;
END;
$$ LANGUAGE plpgsql;

-- 6) Registrar una reserva (turismo) - inserta y deja que los triggers
--    de millas hagan su trabajo. La Flask app la llama vía RPC.
CREATE OR REPLACE FUNCTION prc_registrar_reserva(
  p_cliente_dni VARCHAR,
  p_agencia_id INTEGER,
  p_pasaje_id INTEGER,
  p_hotel_id INTEGER,
  p_circuito_id INTEGER
) RETURNS INTEGER AS $$
DECLARE
  v_reserva_id INTEGER;
BEGIN
  INSERT INTO reserva (cliente_dni, agencia_id, pasaje_id, hotel_id, circuito_id)
  VALUES (p_cliente_dni, p_agencia_id, p_pasaje_id, p_hotel_id, p_circuito_id)
  RETURNING reserva_id INTO v_reserva_id;

  RETURN v_reserva_id;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- ROW LEVEL SECURITY
-- Se habilita explícitamente acá (en vez de dejar que el SQL
-- Editor de Supabase lo agregue solo) para evitar el bug de
-- mayúsculas del auto-detector. Como no definimos políticas,
-- solo la service_role key (la que usa la app Flask) va a poder
-- leer/escribir estas tablas; es la que corresponde para un
-- backend server-side.
-- ============================================================

ALTER TABLE pais ENABLE ROW LEVEL SECURITY;
ALTER TABLE provincia ENABLE ROW LEVEL SECURITY;
ALTER TABLE ciudad ENABLE ROW LEVEL SECURITY;
ALTER TABLE aeropuerto ENABLE ROW LEVEL SECURITY;
ALTER TABLE categoria_cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE agencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE mayorista ENABLE ROW LEVEL SECURITY;
ALTER TABLE agencia_mayorista ENABLE ROW LEVEL SECURITY;
ALTER TABLE hotel ENABLE ROW LEVEL SECURITY;
ALTER TABLE circuito ENABLE ROW LEVEL SECURITY;
ALTER TABLE circuito_ciudad ENABLE ROW LEVEL SECURITY;
ALTER TABLE pasaje ENABLE ROW LEVEL SECURITY;
ALTER TABLE reserva ENABLE ROW LEVEL SECURITY;
ALTER TABLE participante ENABLE ROW LEVEL SECURITY;
ALTER TABLE reserva_participante ENABLE ROW LEVEL SECURITY;
ALTER TABLE bodega ENABLE ROW LEVEL SECURITY;
ALTER TABLE vino ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE movimiento_stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE venta_vino ENABLE ROW LEVEL SECURITY;
ALTER TABLE linea_venta_vino ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- DATOS INICIALES (seed)
-- ============================================================

-- Categorías (idénticas a la tabla del documento original)
INSERT INTO categoria_cliente (nombre, nivel, millas_minimas, descuento_pct, acceso_exclusivo) VALUES
  ('Bronze',   1,     0,  0,  'N'),
  ('Silver',   2,  5000,  5,  'N'),
  ('Gold',     3, 15000, 12,  'S'),
  ('Platinum', 4, 40000, 20,  'S');

-- Agencia (con base en Firmat)
INSERT INTO agencia (cant_empleados, direccion_fisica) VALUES
  (8, 'Av. San Martín 450, Firmat, Santa Fe');

-- Países
INSERT INTO pais (codigo, nombre) VALUES
  ('ARG', 'Argentina'),
  ('BRA', 'Brasil'),
  ('ESP', 'España'),
  ('ITA', 'Italia'),
  ('USA', 'Estados Unidos');

-- Provincias
INSERT INTO provincia (nombre, pais_codigo) VALUES
  ('Santa Fe', 'ARG'),
  ('Río Negro', 'ARG'),
  ('Mendoza', 'ARG'),
  ('Buenos Aires', 'ARG');

-- Ciudades
INSERT INTO ciudad (nombre, provincia_id) VALUES
  ('Firmat', 1),
  ('Rosario', 1),
  ('San Carlos de Bariloche', 2),
  ('Mendoza', 3),
  ('Ciudad de Buenos Aires', 4);

-- Aeropuertos
INSERT INTO aeropuerto (codigo, nombre, cant_vuelos_prom, pais_codigo) VALUES
  ('ROS', 'Aeropuerto Internacional Rosario', 40, 'ARG'),
  ('EZE', 'Aeropuerto Internacional Ministro Pistarini', 320, 'ARG'),
  ('BRC', 'Aeropuerto Internacional Bariloche', 60, 'ARG'),
  ('MDZ', 'Aeropuerto Internacional El Plumerillo', 70, 'ARG'),
  ('GIG', 'Aeropuerto Internacional Rio de Janeiro-Galeão', 150, 'BRA'),
  ('MAD', 'Aeropuerto Adolfo Suárez Madrid-Barajas', 400, 'ESP');

-- Hoteles
INSERT INTO hotel (nombre, categoria, direccion, precio_noche, ciudad_id) VALUES
  ('Hostería Lago Azul', 4, 'Av. Bustillo 3200, Bariloche', 85000, 3),
  ('Refugio Andino Bariloche', 3, 'Av. Pioneros 1400, Bariloche', 55000, 3),
  ('Hotel Bodega & Suites Mendoza', 5, 'Alameda 1200, Mendoza', 120000, 4),
  ('Posada del Sol Mendoza', 3, 'San Martín 900, Mendoza', 48000, 4),
  ('Gran Hotel Buenos Aires', 5, 'Av. Corrientes 800, CABA', 140000, 5);

-- Circuitos
INSERT INTO circuito (denominacion, cant_personas_anual_prom, precio) VALUES
  ('Ruta del Vino Mendocino', 2400, 95000),
  ('Bariloche Aventura: Lagos y Montaña', 3100, 110000),
  ('Buenos Aires Clásica', 5200, 60000);

INSERT INTO circuito_ciudad (circuito_id, ciudad_id) VALUES
  (1, 4), (2, 3), (3, 5);

-- Pasajes
INSERT INTO pasaje (descripcion, horario_vuelo, precio, millas_otorgadas, aero_salida_id, aero_llegada_id) VALUES
  ('Rosario - Bariloche directo', '2026-10-05 08:30:00', 145000, 2500, 'ROS', 'BRC'),
  ('Buenos Aires - Bariloche', '2026-10-06 09:15:00', 130000, 2200, 'EZE', 'BRC'),
  ('Buenos Aires - Mendoza', '2026-10-10 07:00:00', 110000, 1800, 'EZE', 'MDZ'),
  ('Buenos Aires - Rio de Janeiro', '2026-11-02 14:20:00', 210000, 4000, 'EZE', 'GIG'),
  ('Buenos Aires - Madrid', '2026-12-01 22:40:00', 780000, 12000, 'EZE', 'MAD'),
  ('Rosario - Buenos Aires', '2026-10-15 11:00:00', 45000, 600, 'ROS', 'EZE');

-- Bodegas (ficticias)
INSERT INTO bodega (nombre, contacto) VALUES
  ('Bodega Piedra Alta', 'ventas@piedraalta.com.ar'),
  ('Bodega Luna del Valle', 'contacto@lunadelvalle.com.ar'),
  ('Bodega Origen Sur', 'info@origensur.com.ar');

-- Vinos (categoria_minima_id: NULL=todos, 3=Gold, 4=Platinum)
INSERT INTO vino (nombre, varietal, anio, precio, bodega_id, categoria_minima_id) VALUES
  ('Piedra Alta Malbec Clásico',        'Malbec',      2023, 8500,  1, NULL),
  ('Piedra Alta Torrontés',             'Torrontés',   2024, 6200,  1, NULL),
  ('Luna del Valle Cabernet Sauvignon', 'Cabernet Sauvignon', 2022, 9800, 2, NULL),
  ('Luna del Valle Malbec Reserva',     'Malbec',      2021, 18500, 2, 3),
  ('Origen Sur Blend Premium',          'Blend',       2020, 32000, 3, 3),
  ('Origen Sur Gran Corte Limitado',    'Blend',       2019, 65000, 3, 4),
  ('Piedra Alta Chardonnay',            'Chardonnay',  2024, 6800,  1, NULL),
  ('Luna del Valle Malbec Gran Reserva','Malbec',      2018, 78000, 2, 4);

-- Stock inicial
INSERT INTO stock (vino_id, cantidad) VALUES
  (1, 120), (2, 90), (3, 75), (4, 40), (5, 25), (6, 10), (7, 60), (8, 8);

-- ============================================================
-- CATÁLOGO EXTENDIDO (más destinos y vinos, para que el sitio
-- se sienta como un catálogo real y no una demo mínima)
-- ============================================================

-- Provincias nuevas
INSERT INTO provincia (nombre, pais_codigo) VALUES
  ('Salta', 'ARG'),
  ('Tierra del Fuego', 'ARG'),
  ('Misiones', 'ARG');

-- Ciudades nuevas (provincia_id 5=Salta, 6=Tierra del Fuego, 7=Misiones)
INSERT INTO ciudad (nombre, provincia_id) VALUES
  ('Salta', 5),
  ('Ushuaia', 6),
  ('Puerto Iguazú', 7);

-- Aeropuertos nuevos
INSERT INTO aeropuerto (codigo, nombre, cant_vuelos_prom, pais_codigo) VALUES
  ('SLA', 'Aeropuerto Martín Miguel de Güemes', 25, 'ARG'),
  ('USH', 'Aeropuerto Internacional de Ushuaia', 20, 'ARG'),
  ('IGR', 'Aeropuerto Internacional de Cataratas del Iguazú', 35, 'ARG');

-- Hoteles nuevos (ciudad_id 6=Salta, 7=Ushuaia, 8=Puerto Iguazú)
INSERT INTO hotel (nombre, categoria, direccion, precio_noche, ciudad_id) VALUES
  ('Hotel Colonial Salta', 4, 'Balcarce 460, Salta', 62000, 6),
  ('Hostería Fin del Mundo', 4, 'Av. Maipú 750, Ushuaia', 95000, 7),
  ('Selva Hotel Iguazú', 5, 'Selva Paranaense s/n, Puerto Iguazú', 110000, 8);

-- Circuitos nuevos
INSERT INTO circuito (denominacion, cant_personas_anual_prom, precio) VALUES
  ('Norte Argentino: Salta y Los Valles', 1800, 88000),
  ('Patagonia Austral: Ushuaia', 2000, 135000),
  ('Cataratas del Iguazú', 4500, 78000);

INSERT INTO circuito_ciudad (circuito_id, ciudad_id) VALUES
  (4, 6), (5, 7), (6, 8);

-- Pasajes nuevos
INSERT INTO pasaje (descripcion, horario_vuelo, precio, millas_otorgadas, aero_salida_id, aero_llegada_id) VALUES
  ('Buenos Aires - Salta', '2026-10-20 06:45:00', 135000, 1600, 'EZE', 'SLA'),
  ('Buenos Aires - Ushuaia', '2026-11-15 08:00:00', 215000, 3000, 'EZE', 'USH'),
  ('Buenos Aires - Puerto Iguazú', '2026-10-25 10:30:00', 120000, 1200, 'EZE', 'IGR');

-- Bodega nueva (Cafayate, Salta — zona real de Torrontés de altura)
INSERT INTO bodega (nombre, contacto) VALUES
  ('Bodega Altos del Sol', 'ventas@altosdelsol.com.ar');

-- Vinos nuevos
INSERT INTO vino (nombre, varietal, anio, precio, bodega_id, categoria_minima_id) VALUES
  ('Altos del Sol Torrontés de Altura', 'Torrontés', 2024, 7200, 4, NULL),
  ('Altos del Sol Malbec de Altura',    'Malbec',    2022, 21000, 4, 3);

INSERT INTO stock (vino_id, cantidad) VALUES
  (9, 70), (10, 30);

-- Movimientos de stock: carga inicial de todo el catálogo (trazabilidad completa)
INSERT INTO movimiento_stock (vino_id, tipo, cantidad, fecha) VALUES
  (1, 'INGRESO', 120, '2022-01-05'), (2, 'INGRESO', 90, '2022-01-05'),
  (3, 'INGRESO', 75, '2022-01-05'),  (4, 'INGRESO', 40, '2022-01-05'),
  (5, 'INGRESO', 25, '2022-01-05'),  (6, 'INGRESO', 10, '2022-01-05'),
  (7, 'INGRESO', 60, '2022-01-05'),  (8, 'INGRESO', 8,  '2022-01-05'),
  (9, 'INGRESO', 70, '2023-03-10'),  (10, 'INGRESO', 30, '2023-03-10');

-- ============================================================
-- CUENTA DE DEMOSTRACIÓN
-- Cliente con años de uso simulado: reservas repartidas entre
-- 2022 y 2026 que, vía los triggers de millas, lo llevan
-- naturalmente hasta categoría Platinum, más historial de
-- compras en la vinoteca a medida que subía de nivel.
--
-- Login de prueba:
--   DNI:      28456789
--   Password: Vinoteca2026
-- ============================================================

INSERT INTO cliente (dni, nombre, apellido, email, telefono, password_hash, millas_acumuladas, categoria_id) VALUES
  ('28456789', 'Julián', 'Ferreyra', 'julian.ferreyra@example.com', '3465555444',
   'scrypt:32768:8:1$2w75VyopSZ06NFDD$41fdeb2cccf5aef8110dd2638a3d2024c941cc1a4486df89b6f901f6f6e593a5b26aad3d54c03bb04b5d7b625838216d8501b107963c235a89ef08eff82e88bd',
   0, 1);

-- Reservas históricas (el trigger va sumando millas y recalculando
-- la categoría en cada INSERT, en el mismo orden en que se muestran).
INSERT INTO reserva (fecha_reserva, codigo_vuelo, cliente_dni, agencia_id, pasaje_id, hotel_id, circuito_id) VALUES
  ('2022-03-14', 'AR1450', '28456789', 1, 1, NULL, NULL),   -- Rosario-Bariloche, +2500 millas
  ('2022-03-14', NULL,     '28456789', 1, NULL, 1, NULL),   -- Hostería Lago Azul
  ('2022-11-02', 'AR1287', '28456789', 1, 3, NULL, NULL),   -- BA-Mendoza, +1800 millas
  ('2022-11-02', NULL,     '28456789', 1, NULL, NULL, 1),   -- Ruta del Vino Mendocino
  ('2023-06-20', 'AR1780', '28456789', 1, 4, NULL, NULL),   -- BA-Rio, +4000 millas
  ('2024-01-10', 'AR1075', '28456789', 1, 5, NULL, NULL),   -- BA-Madrid, +12000 millas
  ('2024-08-05', 'AR1320', '28456789', 1, 2, NULL, NULL),   -- BA-Bariloche, +2200 millas
  ('2024-08-05', NULL,     '28456789', 1, NULL, NULL, 2),   -- Bariloche Aventura
  ('2025-02-18', 'AR1502', '28456789', 1, 7, NULL, NULL),   -- BA-Salta, +1600 millas
  ('2025-02-18', NULL,     '28456789', 1, NULL, NULL, 4),   -- Norte Argentino
  ('2025-09-30', 'AR1075', '28456789', 1, 5, NULL, NULL),   -- BA-Madrid otra vez, +12000 millas
  ('2026-01-15', 'AR1611', '28456789', 1, 9, NULL, NULL),   -- BA-Iguazú, +1200 millas
  ('2026-01-15', NULL,     '28456789', 1, NULL, 8, NULL),   -- Selva Hotel Iguazú
  ('2026-05-22', 'AR1690', '28456789', 1, 8, NULL, NULL),   -- BA-Ushuaia, +3000 millas -> cruza a Platinum
  ('2026-05-22', NULL,     '28456789', 1, NULL, NULL, 5);   -- Patagonia Austral

-- Compras de vinoteca a lo largo de los años (el % de descuento
-- refleja la categoría que tenía en cada momento; los vinos
-- exclusivos ya pasan la validación porque para cuando se insertan
-- el cliente arriba ya quedó en Platinum tras las reservas).
INSERT INTO venta_vino (cliente_dni, fecha, total, descuento_aplicado) VALUES
  ('28456789', '2022-04-01', 17000,  0),   -- Bronze: Piedra Alta Malbec x2
  ('28456789', '2023-08-10', 17670,  5),   -- Silver: Piedra Alta Torrontés x3
  ('28456789', '2024-03-05', 16280, 12),   -- Gold: Luna del Valle Malbec Reserva (exclusivo Gold)
  ('28456789', '2025-06-12', 28160, 12),   -- Gold: Origen Sur Blend Premium (exclusivo Gold)
  ('28456789', '2026-06-01', 52000, 20),   -- Platinum: Origen Sur Gran Corte Limitado (exclusivo Platinum)
  ('28456789', '2026-06-10', 62400, 20);   -- Platinum: Luna del Valle Malbec Gran Reserva (exclusivo Platinum)

INSERT INTO linea_venta_vino (venta_id, vino_id, cantidad, precio_unitario) VALUES
  (1, 1, 2, 8500),
  (2, 2, 3, 6200),
  (3, 4, 1, 18500),
  (4, 5, 1, 32000),
  (5, 6, 1, 65000),
  (6, 8, 1, 78000);

-- Movimientos de stock (salida) que reflejan esas compras
INSERT INTO movimiento_stock (vino_id, tipo, cantidad, fecha) VALUES
  (1, 'SALIDA', 2, '2022-04-01'),
  (2, 'SALIDA', 3, '2023-08-10'),
  (4, 'SALIDA', 1, '2024-03-05'),
  (5, 'SALIDA', 1, '2025-06-12'),
  (6, 'SALIDA', 1, '2026-06-01'),
  (8, 'SALIDA', 1, '2026-06-10');

UPDATE stock SET cantidad = cantidad - 2, ultima_actualizacion = '2022-04-01' WHERE vino_id = 1;
UPDATE stock SET cantidad = cantidad - 3, ultima_actualizacion = '2023-08-10' WHERE vino_id = 2;
UPDATE stock SET cantidad = cantidad - 1, ultima_actualizacion = '2024-03-05' WHERE vino_id = 4;
UPDATE stock SET cantidad = cantidad - 1, ultima_actualizacion = '2025-06-12' WHERE vino_id = 5;
UPDATE stock SET cantidad = cantidad - 1, ultima_actualizacion = '2026-06-01' WHERE vino_id = 6;
UPDATE stock SET cantidad = cantidad - 1, ultima_actualizacion = '2026-06-10' WHERE vino_id = 8;
